### ISSUE TITLE
两级联动自己添加的数据,当一级二级选中的全是第一项时,点击确定按钮报错,但是如果选中其他项时没问题

### ISSUE THREAD

**Issue by zxyaust** [gzu-liyujiang/AndroidPicker#159]
java.lang.IndexOutOfBoundsException: Invalid index 8, size is 4
                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                  at cn.qqtheme.framework.picker.LinkagePicker.getSelectedSecondItem(LinkagePicker.java:185)
                                                                  at cn.qqtheme.framework.picker.LinkagePicker.onSubmit(LinkagePicker.java:401)
                                                                  at cn.qqtheme.framework.popup.ConfirmPopup$2.onClick(ConfirmPopup.java:400)
                                                                  at android.view.View.performClick(View.java:5267)
                                                                  at android.view.View$PerformClick.run(View.java:21249)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by zxyaust** [comment]
下面是piker代码:    
LinkagePicker picker = new LinkagePicker(this, new MyPikerDataProvider());
        picker.setCycleDisable(true);
        picker.setUseWeight(true);
        picker.setSelectedIndex(0, 8);
        //picker.setSelectedItem("12", "9");
        picker.setContentPadding(10, 0);
        picker.setOnWheelLinkageListener(new LinkagePicker.OnWheelLinkageListener() {
            @Override
            public void onLinkage(int firstIndex, int secondIndex, int thirdIndex) {
                NongshijiluNongZiListBean.GoodsListBean bean = mList.get(firstIndex).goods_list.get(secondIndex);
                name = bean.goods_name;
                unit = bean.goods_unit;
                mGoodsBean.name = name;
                mGoodsBean.goods_id = bean.goods_id;
                mTvName.setText(name);
            }
        });
        picker.show();

**Comment by zxyaust** [comment]
Dataprovider代码:
   
 class MyPikerDataProvider implements LinkagePicker.Provider<NongshijiluNongZiListBean, NongshijiluNongZiListBean.GoodsListBean, Void> {

        @Override
        public boolean isOnlyTwo() {
            return true;
        }

        @NonNull
        @Override
        public List<NongshijiluNongZiListBean> initFirstData() {
            return mList;
        }

        @NonNull
        @Override
        public List<NongshijiluNongZiListBean.GoodsListBean> linkageSecondData(int firstIndex) {
            return mList.get(firstIndex).goods_list;
        }

        @NonNull
        @Override
        public List<Void> linkageThirdData(int firstIndex, int secondIndex) {
            return new ArrayList<>();
        }
    }

**Comment by zxyaust** [comment]
一级bean对象:
public class NongshijiluNongZiListBean implements Serializable, LinkageFirst<NongshijiluNongZiListBean.GoodsListBean> {


    public String second_type_name;
    public List<GoodsListBean> goods_list;


    @Override
    public List<GoodsListBean> getSeconds() {
        return goods_list;
    }

    @Override
    public Object getId() {
        return null;
    }

    @Override
    public String getName() {
        return second_type_name;
    }
}

**Comment by zxyaust** [comment]
二级bean对象:   
 public static class GoodsListBean implements LinkageSecond<Void> {

        public String goods_id;
        public String goods_name;
        public String goods_unit;

        @Override
        public List<Void> getThirds() {
            return null;
        }

        @Override
        public Object getId() {
            return goods_id;
        }

        @Override
        public String getName() {
            return goods_name;
        }
    }

**Comment by liyujiang-gzu** [comment]
@zxyaust picker.setSelectedIndex(0, 8);
实际项目中这一句代码这样用是不科学的，你默认选择第一级的第一项和第二级的第9项，第一级第一项的数据里不一定有这么多数据

**Comment by liyujiang-gzu** [comment]
java.lang.IndexOutOfBoundsException: Invalid index 8, size is 4

你这个报错很明显，第一级第一项只有4条数据，无法选择所以为8的第九项

**Comment by zxyaust** [comment]
嗯,明白了,谢谢啊 picker.setSelectedIndex(0, 8);是这个代码的问题,
