### ISSUE TITLE
1.4新版本，4.4系统兼容性问题

### ISSUE THREAD

**Issue by Tandrow** [gzu-liyujiang/AndroidPicker#79]
在4.4系统上出现类型转换异常问题，又来博主找小虫子了
`java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
at android.widget.ListView.measureScrapChild(ListView.java:1183)
at android.widget.ListView.onMeasure(ListView.java:1149)
at cn.qqtheme.framework.widget.WheelView.onMeasure(WheelView.java:473)
at android.view.View.measure(View.java:16497)`

**Comment by liyujiang-gzu** [comment]
这样啊，难怪有个同胞说会奔溃，我死活遇不到。稍后改改
