### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by fangood** [gzu-liyujiang/AndroidPicker#8]
java.lang.NullPointerException
            at com.hiayi.dialog.wheelpicker.widget.WheelView.setBackgroundDrawable(WheelView.java:246)
            at com.hiayi.dialog.wheelpicker.widget.WheelView.setBackground(WheelView.java:239)
            at android.view.View.<init>(View.java:3654)
            at android.view.ViewGroup.<init>(ViewGroup.java:436)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at android.widget.ScrollView.<init>(ScrollView.java:161)
            at android.widget.ScrollView.<init>(ScrollView.java:157)
            at android.widget.ScrollView.<init>(ScrollView.java:153)
            at com.hiayi.dialog.wheelpicker.widget.WheelView.<init>(WheelView.java:95)
            at com.hiayi.dialog.wheelpicker.picker.AddressPicker.makeCenterView(AddressPicker.java:133)
            at com.hiayi.dialog.common.popup.ConfirmPopup.makeContentView(ConfirmPopup.java:190)
            at com.hiayi.dialog.common.popup.BottomPopup.onShowPrepare(BottomPopup.java:63)
            at com.hiayi.dialog.common.popup.BottomPopup.show(BottomPopup.java:178)
            at cn.com.android.hiayi.activity.AProfileActivity.addressChooseDialog(AProfileActivity.java:373)
            at cn.com.android.hiayi.activity.AProfileActivity.onClick(AProfileActivity.java:199)
            at android.view.View.performClick(View.java:4211)
            at android.view.View$PerformClick.run(View.java:17446)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5305)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by liyujiang-gzu** [comment]
null异常好解决，com.hiayi.dialog.wheelpicker.widget.WheelView的第246行，看哪个对象可能是null？

**Comment by fangood** [comment]
`public void setBackgroundDrawable(Drawable background) {
        if (viewWidth == 0) {
            viewWidth = ((Activity) context).getWindowManager().getDefaultDisplay().getWidth();
            LogUtils.debug(this, "viewWidth: " + viewWidth);
        }`
context 为null，只是提一下，如有打扰，非常抱歉

**Comment by fangood** [comment]
activity中没有设置android:theme时会先调用WheelView中的setBackground导致context为空出现空指针异常。
