### ISSUE TITLE
Android adk版本19 有重大bug

### ISSUE THREAD

**Issue by zhangyouxin** [gzu-liyujiang/AndroidPicker#87]
调用DatePicker的时候出现这个（sdk23就没有这个问题）
**E/  AndroidRuntime: FATAL EXCEPTION: main**
                 **Process: com.sihaiwanlian.nev, PID: 2201**
                 **java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to**                **android.widget.AbsListView$LayoutParams**
                      **at android.widget.ListView.measureScrapChild(ListView.java:1183)**
                     **at android.widget.ListView.onMeasure(ListView.java:1149)**
                      **at cn.qqtheme.framework.widget.WheelView.onMeasure(WheelView.java:473)**
                    `at android.view.View.measure(View.java:16525)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                      at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
                      at android.view.View.measure(View.java:16525)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                      at android.view.View.measure(View.java:16525)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                      at android.view.View.measure(View.java:16525)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                      at android.view.View.measure(View.java:16525)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                      at android.view.View.measure(View.java:16525)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                      at android.view.View.measure(View.java:16525)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1955)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1127)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1334)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                      at android.view.Choreographer.doFrame(Choreographer.java:544)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5113)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                      at dalvik.system.NativeStart.main(Native Method)`

**Comment by Tandrow** [comment]
查看一下作者的更新日志，这个新版本应该是修复好了的

**Comment by liyujiang-gzu** [comment]
最新新版本我记得是改过这个问题

**Comment by liyujiang-gzu** [comment]
参见#79及[5776ca04faef854ea73579d6702d4ad2de5c365f](https://github.com/gzu-liyujiang/AndroidPicker/commit/5776ca04faef854ea73579d6702d4ad2de5c365f)
